[package]
name = "vortex-sampling"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Composable sampling combinators for generating columnar test data"
readme.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
rand = { workspace = true }

[lints]
workspace = true
